Repository Ureka-High-Five/frontend, pull requests merged in 2025-08, with the labels that each got.

#51 [FEAT] [HIGH-55] QA 사항 반영: 홈페이지에서 상세 정보 프리패칭 및 디자인 수정
  src/components/Home/atom/ContentCard.tsx
  src/components/Home/molecule/RecommendationSection.tsx
  src/components/Home/organism/MainRecommendBanner.tsx
  src/components/contentDetail/ContentDetailLayout.tsx
  src/components/contentDetail/organism/ContentVideo.tsx
  src/hooks/common/usePrefetchContentOnView.ts
  src/hooks/queries/content/useContentDetailQuery.ts
  src/hooks/queries/content/useInfiniteContentReviewsQuery.ts
  src/hooks/queries/content/useMyReviewQuery.ts
Labels: 🌟Feature, Review effort 3/5

#52 [REFACTOR] [HIGH-63] useHlsMedia함수 역할 분리
  src/hooks/shorts/useHlsMedia.ts
Labels: 🔨Refactor, Review effort 3/5

#53 [REFACTOR] [HIGH-57] 온보딩, 큐레이션 QA 수정 및 콘텐츠 등록 구현
  src/apis/common/getContentPresignedUrl.ts
  src/components/My/MyLayout.tsx
  src/components/My/molecule/MyReviewItem.tsx
  src/components/My/molecule/SearchContentList.tsx
  src/components/My/organism/CurationTab.tsx
  src/components/My/organism/MyPageTabs.tsx
  src/components/My/organism/ReviewTab.tsx
  src/components/OnBoarding/OnBoardingLayout.tsx
  src/components/OnBoarding/molecule/OnBoardingContentCard.tsx
  src/components/OnBoarding/organism/ContentSelect.tsx
  src/components/OnBoarding/organism/GenderSelect.tsx
  src/components/OnBoarding/organism/Name.tsx
  src/components/admin/content-modal.tsx
  src/components/common/Header.tsx
  src/hooks/common/useFileUpload.ts
  src/hooks/queries/curation/useMyCurationInfiniteQuery.ts
  src/hooks/queries/onboarding/useUserPreferenceMutation.ts
  src/pages/OnBoardingPage.tsx
  src/stores/useUserStore.ts
  src/types/content.d.ts
  src/types/user.d.ts
Labels: 🌟Feature, 🔨Refactor, Review effort 4/5

#55 [FEAT] [HIGH-65] 초기 렌더링 향상을 위한 번들 최적화
  .gitignore
  package-lock.json
  package.json
  src/hooks/common/useDebouncedValue.ts
  vite.config.ts
Labels: 🌟Feature, Review effort 2/5

#57 [FEAT] [HIGH-66] QA 사항 반영 및 클릭 로깅 API 연동
  src/apis/content/postContentClick.ts
  src/apis/shorts/getShortsById.ts
  src/components/Home/molecule/RecommendationSection.tsx
  src/components/search/organism/SearchContentList.tsx
  src/components/shorts/organism/ReelCard.tsx
  src/components/shorts/organism/ReelOverlay.tsx
  src/constants/api.ts
  src/hooks/queries/content/useContentClickMutation.ts
  src/hooks/queries/shorts/useCommentMutation.ts
  src/hooks/queries/shorts/useCommentQuery.ts
Labels: 🌟Feature, Review effort 3/5

#58 [FEAT] [HIGH-68] 쇼츠, 모달 QA 수정 및 금칙어 검사
  src/apis/onboarding/postSlangCheck.ts
  src/components/My/organism/CreateCurationModal.tsx
  src/components/OnBoarding/OnBoardingLayout.tsx
  src/components/OnBoarding/organism/GenderSelect.tsx
  src/components/OnBoarding/organism/Name.tsx
  src/constants/api.ts
  src/hooks/common/useOutsideClick.ts
  src/hooks/queries/onboarding/useSlangCheckMutation.ts
  src/hooks/queries/shorts/useShortsInfiniteQuery.ts
  src/pages/OnBoardingPage.tsx
  src/types/onBoarding.d.ts
Labels: 🌟Feature, Review effort 3/5
