Repository Ureka-High-Five/frontend, pull requests merged in 2025-07, with the labels that each got.

#1 HIGH-15 프로젝트 초기 설정
  .eslintrc.cjs
  .husky/commit-msg
  .prettierrc.json
  commitlint.config.cjs
  components.json
  eslint.config.js
  index.html
  package-lock.json
  package.json
  postcss.config.js
  src/App.tsx
  src/AppRouter.tsx
  src/apis/api.txt
  src/components/component.txt
  src/constants/path.ts
  src/hooks/queries/common/queryClient.ts
  src/index.css
  src/main.tsx
  src/pages/LandingPage.tsx
  src/pages/page.txt
  src/types/type.txt
  src/utils/cn.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: ⚙️Configuration

#4 [FEAT] [HIGH-18] 텍스트 스타일 적용
  .eslintrc.cjs
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc.json
  README.md
  commitlint.config.cjs
  components.json
  index.html
  package-lock.json
  package.json
  postcss.config.js
  src/App.tsx
  src/AppRouter.tsx
  src/components/common/CommonButton.tsx
  src/components/ui/button.tsx
  src/constants/path.ts
  src/hooks/queries/common/queryClient.ts
  src/index.css
  src/main.tsx
  src/pages/LandingPage.tsx
  src/utils/cn.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 🎨Design

#5 [CHORE] [HIGH-21] PR Agent 설정
  .github/workflows/pr_agent.yml
  .pr_agent.yaml
Labels: Review effort 2/5

#3 [FEAT] [HIGH-20] 랜딩 페이지 UI 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/logo.png
  src/assets/react.svg
  src/components/common/CommonButton.tsx
  src/components/landing/AnimatedLogo.tsx
  src/components/landing/AnimatedSubText.tsx
  src/components/landing/LandingLayout.tsx
  src/components/landing/SocialLoginButton.tsx
  src/pages/LandingPage.tsx
Labels: 🎨Design

#6 [FEAT] [HIGH-19] 공통 레이아웃 및 하단 네비게이션 바, Avatar 컴포넌트 구현
  src/AppRouter.tsx
  src/components/Home/HomeLayout.tsx
  src/components/Nav/NavItem.tsx
  src/components/Nav/NavigationBar.tsx
  src/components/ui/avatar.tsx
  src/constants/path.ts
Labels: 🎨Design

#7 [FEAT] [HIGH-22] 공통 응답 형식 기반 API 에러 처리 로직 구현
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  src/apis/HTTPError.ts
  src/apis/api.txt
  src/apis/auth/postNewToken.ts
  src/apis/axiosInstance.ts
  src/apis/axiosInterceptors.ts
  src/constants/api.ts
  src/types/auth.d.ts
  src/types/axios.d.ts
  src/types/type.txt
Labels: 🌟Feature, Review effort 2/5

#9 [REFACTOR] [HIGH-14] animation atom 분리
  src/components/common/atom/AnimatedButtonEntrance.tsx
  src/components/common/atom/AnimatedFadeIn.tsx
  src/components/common/atom/AnimatedImageEntrance.tsx
  src/components/component.txt
  src/components/contentDetail/ContentDetailLayout.tsx
  src/components/contentDetail/molecules/RatingMessage.tsx
  src/components/contentDetail/molecules/ReviewInput.tsx
  src/components/contentDetail/molecules/ReviewItem.tsx
  src/components/contentDetail/molecules/StarRating.tsx
  src/components/contentDetail/organism/ReviewForm.tsx
  src/components/contentDetail/organism/ReviewList.tsx
  src/components/landing/AnimatedLogo.tsx
  src/components/landing/AnimatedSubText.tsx
  src/components/landing/SocialLoginButton.tsx
  src/components/landing/organism/AnimatedLogo.tsx
  src/components/landing/organism/AnimatedSubText.tsx
  src/components/landing/organism/SocialLoginButton.tsx
  src/pages/ContentDetailPage.tsx
  src/pages/LandingPage.tsx
Labels: 🌟Feature, Review effort 3/5

#10 [FEAT] [HIGH-25] 홈 페이지 UI
  src/AppRouter.tsx
  src/components/Home/HomeLayout.tsx
  src/components/Home/atom/ContentCard.tsx
  src/components/Home/molecule/RecommendationSection.tsx
  src/components/Home/organism/CurationRecommendSection.tsx
  src/components/Home/organism/GenreRecommendSection.tsx
  src/components/Home/organism/MainRecommendBanner.tsx
  src/components/Home/organism/PersonalRecommendSection.tsx
  src/components/common/AvatarWithText.tsx
  src/components/common/Header.tsx
  src/components/common/HorizontalScrollContainer.tsx
  src/components/common/Navigation/NavItem.tsx
  src/components/common/Navigation/NavigationBar.tsx
  src/components/ui/input.tsx
  src/pages/Home/HomePage.tsx
  src/pages/Home/__mock__/mockRecommendContents.ts
  src/types/RecommendContentsResponse.d.ts
Labels: 🌟Feature, Review effort 3/5

#11 [FEAT] [HIGH-23] 소셜(카카오) 로그인 구현
  package.json
  src/AppRouter.tsx
  src/apis/auth/postKakaoLogin.ts
  src/components/landing/organism/SocialLoginButton.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/hooks/queries/auth/useKakaoLoginMutation.ts
  src/pages/RedirectPage.tsx
  src/stores/useUserStore.ts
  src/types/auth.d.ts
Labels: 🌟Feature

#15 [FEAT] [HIGH-29] 홈 화면 추천 콘텐츠 API 연동
  src/apis/home/getPreviewVideo.ts
  src/apis/home/getRecommendContents.ts
  src/components/Home/atom/ContentCard.tsx
  src/components/Home/atom/VisibleSection.tsx
  src/components/Home/molecule/RecommendationSection.tsx
  src/components/Home/organism/MainRecommendBanner.tsx
  src/components/common/HorizontalScrollContainer.tsx
  src/constants/api.ts
  src/hooks/queries/home/usePreviewVideoQuery.ts
  src/hooks/queries/home/useRecommendQuery.ts
  src/pages/Home/HomePage.tsx
  src/pages/Home/__mock__/mockRecommendContents.ts
  src/pages/HomePage.tsx
  src/types/RecommendContentsResponse.d.ts
  src/types/content.d.ts
Labels: 🌟Feature, Review effort 3/5

#18 [DEPLOY] version 1.0.2
  vercel.json
Labels: Review effort 1/5

#20 [FEAT] content detail 페이지 무한스크롤 공통 훅 연동
  src/components/Home/molecule/RecommendationSection.tsx
  src/components/contentDetail/ContentDetailLayout.tsx
  src/components/contentDetail/molecules/ReviewItem.tsx
  src/components/contentDetail/organism/ReviewForm.tsx
  src/hooks/common/useIntersectionObserver.ts
  src/hooks/common/useScrollPositionDetector.ts
  src/hooks/queries/content/useContentDetailQuery.ts
  src/hooks/queries/content/useInfiniteContentReviewsQuery.ts
  src/hooks/queries/content/useMyReviewMutation.ts
  src/hooks/queries/content/useMyReviewQuery.ts
  src/pages/ContentDetailPage.tsx
  src/pages/page.txt
Labels: 🔨Refactor, Review effort 3/5

#22 [FEAT] [HIGH-33] shorts comment, like API연동
  src/apis/shorts/getShortsComment.ts
  src/apis/shorts/getShortsLike.ts
  src/apis/shorts/postShortsComment.ts
  src/apis/shorts/postShortsDislike.ts
  src/apis/shorts/postShortsLike.ts
  src/components/shorts/organism/ReelCard.tsx
  src/constants/api.ts
  src/hooks/queries/shorts/useCommentMutation.ts
  src/hooks/queries/shorts/useCommentQuery.ts
  src/hooks/queries/shorts/useDislikeMutation.ts
  src/hooks/queries/shorts/useLikeMutation.ts
  src/hooks/queries/shorts/useLikeQuery.ts
  src/types/shorts.d.ts
Labels: ⚙️Configuration, Review effort 3/5

#21 [FEAT] [HIGH-27] shorts 영상 API 연동 및 무한스크롤 구현
  src/apis/shorts/getShorts.ts
  src/components/shorts/ShortsLayout.tsx
  src/components/shorts/organism/ReelCard.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/hooks/queries/shorts/useShortsInfiniteQuery.ts
  src/pages/HomePage.tsx
  src/pages/ShortsPage.tsx
  src/types/shorts.d.ts
Labels: Review effort 3/5

#25 [FEAT] [HIGH-27] 쇼츠 영상 스트리밍 및 URL 전환
  package.json
  src/AppRouter.tsx
  src/apis/home/getPreviewVideo.ts
  src/apis/home/getRecommendContents.ts
  src/apis/home/getSearchContents.ts
  src/apis/shorts/getShorts.ts
  src/apis/shorts/getShortsById.ts
  src/apis/shorts/getShortsComment.ts
  src/apis/shorts/getShortsLike.ts
  src/apis/shorts/postShortsComment.ts
  src/apis/shorts/postShortsDislike.ts
  src/apis/shorts/postShortsLike.ts
  src/components/shorts/ShortsLayout.tsx
  src/components/shorts/atom/ReelTitle.tsx
  src/components/shorts/molecules/ReelActionBar.tsx
  src/components/shorts/molecules/ReelComment.tsx
  src/components/shorts/organism/ReelCard.tsx
  src/components/shorts/organism/ReelOverlay.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/hooks/queries/shorts/useCommentMutation.ts
  src/hooks/queries/shorts/useCommentQuery.ts
  src/hooks/queries/shorts/useDislikeMutation.ts
  src/hooks/queries/shorts/useLikeMutation.ts
  src/hooks/queries/shorts/useLikeQuery.ts
  src/hooks/queries/shorts/useShortsByIdQuery.ts
  src/hooks/queries/shorts/useShortsInfiniteQuery.ts
  src/hooks/shorts/useActiveShortsId.ts
  src/hooks/shorts/useShortsToShow.ts
  src/pages/HomePage.tsx
  src/pages/ShortsPage.tsx
  src/types/RecommendContentsResponse.d.ts
  src/types/comment.d.ts
  src/types/shorts.d.ts
Labels: 🌟Feature

#24 [FEAT] [HIGH-32] 온보딩 컨텐츠 검색 기능 구현
  package-lock.json
  package.json
  src/apis/home/getSearchContents.ts
  src/components/OnBoarding/OnBoardingLayout.tsx
  src/components/OnBoarding/organism/ContentSelect.tsx
  src/components/contentDetail/ContentDetailLayout.tsx
  src/constants/onBoarding.ts
  src/hooks/common/useDebouncedValue.ts
  src/hooks/common/useIntersectionObserver.ts
  src/hooks/onboarding/useSearchContent.ts
  src/hooks/queries/content/useInfiniteContentReviewsQuery.ts
  src/hooks/queries/home/useSearchContentsInfiniteQuery.ts
  src/pages/ContentDetailPage.tsx
  src/types/search.d.ts
Labels: 🌟Feature, Review effort 4/5

#27 [FEAT] [HIGH-36] 타임라인 기능 및 시점별 댓글 조회 기능 구현
  src/apis/home/getSearchContents.ts
  src/apis/shorts/getShorts.ts
  src/apis/shorts/getShortsCommentsTimeline.ts
  src/components/common/AvatarWithText.tsx
  src/components/common/Navigation/NavigationBar.tsx
  src/components/shorts/ShortsLayout.tsx
  src/components/shorts/molecules/ReelProgressBar.tsx
  src/components/shorts/organism/ReelCard.tsx
  src/components/shorts/organism/ReelOverlay.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/hooks/queries/shorts/useCommentQuery.ts
  src/hooks/queries/shorts/useCommentTimelineQuery.ts
  src/hooks/queries/shorts/useDislikeMutation.ts
  src/hooks/queries/shorts/useLikeMutation.ts
  src/hooks/queries/shorts/useLikeQuery.ts
  src/hooks/queries/shorts/useShortsInfiniteQuery.ts
  src/hooks/shorts/useCommentTimeline.ts
  src/hooks/shorts/useHlsMedia.ts
  src/hooks/shorts/useLikeTimeline.ts
  src/hooks/shorts/useShortsLikeInfo.ts
  src/hooks/shorts/useShortsToShow.ts
  src/hooks/shorts/useTotalLikeCount.ts
  src/hooks/shorts/useVideoPlayer.ts
  src/hooks/shorts/useVideoTimeTracker.ts
  src/hooks/shorts/videoEventBus.ts
  src/types/shorts.d.ts
  src/utils/groupCommentsByTime.ts
Labels: Review effort 4/5

#30 [FEAT] [HIGH-37] 큐레이션 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/AppRouter.tsx
  src/apis/common/getPresignedUrl.ts
  src/apis/common/putFileUpload.ts
  src/apis/my/curation/deleteMyCuration.ts
  src/apis/my/curation/getCurationDetail.ts
  src/apis/my/curation/getMyCuration.ts
  src/apis/my/curation/postMyCuration.ts
  src/assets/svg/check-circle.svg
  src/assets/svg/index.ts
  src/assets/svg/warning-circle.svg
  src/components/My/MyLayout.tsx
  src/components/My/molecule/CurationDetailList.tsx
  src/components/My/molecule/CurationForm.tsx
  src/components/My/molecule/Profile.tsx
  src/components/My/molecule/SearchContentList.tsx
  src/components/My/molecule/SelectedContentList.tsx
  src/components/My/organism/CreateCurationModal.tsx
  src/components/My/organism/CurationTab.tsx
  src/components/My/organism/MyCurationItem.tsx
  src/components/My/organism/MyPageTabs.tsx
  src/components/My/organism/ReviewTab.tsx
  src/components/ui/sonner.tsx
  src/components/ui/tabs.tsx
  src/components/ui/textarea.tsx
  src/constants/api.ts
  src/hooks/common/useFileUpload.ts
  src/hooks/common/useOverlay.ts
  src/hooks/my/useContentSelector.ts
  src/hooks/my/useCurationSubmit.ts
  src/hooks/queries/common/useFileUploadMutation.ts
  src/hooks/queries/curation/useCreateCurationMutation.ts
  src/hooks/queries/curation/useCurationDetailQuery.ts
  src/hooks/queries/curation/useDeleteCurationMutation.ts
  src/hooks/queries/curation/useMyCurationInfiniteQuery.ts
  src/pages/MyPage.tsx
  src/types/curation.d.ts
  src/utils/generateThumbnailImages.ts
  src/utils/makeToast.tsx
Labels: 🌟Feature

#31 [Feat] [HIGH- 40] 쇼츠 전체 코멘트 조회 API
  package.json
  src/apis/shorts/getAllShortsComments.ts
  src/apis/shorts/getShortsCommentsTimeline.ts
  src/components/common/AvatarWithText.tsx
  src/components/shorts/atom/ReelTitle.tsx
  src/components/shorts/organism/ReelCard.tsx
  src/components/shorts/organism/ReelOverlay.tsx
  src/components/ui/drawer.tsx
  src/constants/api.ts
  src/hooks/common/useIntersectionObserver.ts
  src/hooks/queries/shorts/useCommentInfiniteQuery.ts
  src/hooks/queries/shorts/useCommentTimelineQuery.ts
  src/hooks/queries/shorts/useDislikeMutation.ts
  src/hooks/queries/shorts/useLikeMutation.ts
  src/hooks/queries/shorts/useLikeQuery.ts
  src/hooks/shorts/useCommentTimeline.ts
  src/hooks/shorts/useHlsMedia.ts
  src/hooks/shorts/useShortsLikeInfo.ts
  src/hooks/shorts/useVideoPlayer.ts
  src/types/shorts.d.ts
Labels: 🌟Feature, Review effort 3/5

#32 [FEAT] [HIGH-41] admin 기능
  package.json
  src/AppRouter.tsx
  src/apis/admin/getAllUsers.ts
  src/apis/admin/getUserByName.ts
  src/apis/admin/patchContent.ts
  src/apis/admin/patchUserRole.ts
  src/apis/admin/postContent.ts
  src/apis/shorts/getShorts.ts
  src/components/admin/content-management.tsx
  src/components/admin/content-modal.tsx
  src/components/admin/header.tsx
  src/components/admin/sidebar.tsx
  src/components/admin/user-management.tsx
  src/components/admin/user-role-modal.tsx
  src/components/ui/badge.tsx
  src/components/ui/dialog.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/table.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/hooks/common/useIsMobile.ts
  src/hooks/queries/admin/useDeleteContentMutation.ts
  src/hooks/queries/admin/usePatchContentMutation.ts
  src/hooks/queries/admin/usePatchUserRoleMutation.ts
  src/hooks/queries/admin/usePostContentMutation.ts
  src/hooks/queries/admin/useUserByNameInfiniteQuery.ts
  src/hooks/queries/admin/useUsersInfiniteQuery.ts
  src/hooks/queries/content/useContentDetailQuery.ts
  src/pages/AdminPage.tsx
  src/pages/ContentDetailPage.tsx
  src/types/admin.d.ts
  src/types/content.d.ts
Labels: 🌟Feature, Review effort 4/5

#34 [FEAT] [HIGH-46] 온보딩 컨텐츠 추천 기능 수정
  src/apis/onboarding/postOnBoardingContent.ts
  src/components/My/organism/MyCurationItem.tsx
  src/components/OnBoarding/molecule/OnBoardingContentCard.tsx
  src/components/common/atom/FallbackImage.tsx
  src/pages/OnBoardingPage.tsx
  src/utils/mergeUniqueContents.ts
Labels: 🌟Feature, Review effort 2/5

#35 [FEAT] [HIGH-47] 로딩 및 에러처리 통합
  package.json
  src/components/Home/HomeContentContainer.tsx
  src/components/Home/HomeErrorFallback.tsx
  src/components/Home/atom/ContentCard.tsx
  src/components/Home/atom/VisibleSection.tsx
  src/components/Home/molecule/RecommendationSection.tsx
  src/components/Home/organism/CurationRecommendSection.tsx
  src/components/Home/organism/GenreRecommendSection.tsx
  src/components/Home/organism/MainRecommendBanner.tsx
  src/components/common/AsyncBoundary.tsx
  src/components/common/ErrorFallback.tsx
  src/components/shorts/molecules/ReelActionBar.tsx
  src/components/shorts/molecules/ReelComment.tsx
  src/constants/api.ts
  src/hooks/common/useScrollPositionDetector.ts
  src/hooks/queries/content/useContentDetailQuery.ts
  src/hooks/queries/content/useMyReviewQuery.ts
  src/hooks/queries/home/useRecommendQuery.ts
  src/pages/ContentDetailPage.tsx
  src/pages/HomePage.tsx
  src/types/RecommendContentsResponse.d.ts
Labels: 🌟Feature, Review effort 3/5

#38 [FEAT] [HIGH-53] 사용자 타입에 따른 HLS 설정 최적화 및 ABR 로직 개선
  src/AppRouter.tsx
  src/apis/shorts/getShortsLike.ts
  src/components/admin/content-modal.tsx
  src/components/contentDetail/ContentDetailLayout.tsx
  src/components/shorts/ShortsLayout.tsx
  src/components/shorts/organism/ReelCard.tsx
  src/components/shorts/organism/ReelOverlay.tsx
  src/hooks/shorts/useAvgWatchTimeCalculator.ts
  src/hooks/shorts/useHlsMedia.ts
  src/hooks/shorts/useShortsLikeInfo.ts
  src/hooks/shorts/useShortsWatchTimeTracker.ts
  src/stores/useAudioStore.ts
  src/stores/useUserBehaviorStore.ts
  src/types/shorts.d.ts
  src/utils/classifyUser.ts
Labels: 🌟Feature, Review effort 3/5

#39 [FEAT] [HIGH-52] 1차 QA 사항
  src/App.tsx
  src/components/Home/atom/ContentCard.tsx
  src/components/Home/molecule/RecommendationSection.tsx
  src/components/Home/organism/CurationRecommendSection.tsx
  src/components/Home/organism/MainRecommendBanner.tsx
  src/components/My/MyLayout.tsx
  src/components/admin/content-modal.tsx
  src/components/admin/header.tsx
  src/components/common/Header.tsx
  src/components/common/atom/LazyImage.tsx
  src/components/contentDetail/ContentDetailLayout.tsx
  src/components/contentDetail/molecules/EmptyReviewMessage.tsx
  src/components/contentDetail/organism/ContentMainInfo.tsx
  src/components/contentDetail/organism/ReviewList.tsx
  src/components/search/molecules/SearchContentItem.tsx
  src/components/search/organism/SearchContentList.tsx
  src/components/shorts/ShortsLayout.tsx
  src/components/shorts/organism/ReelCard.tsx
  src/components/ui/skeleton.tsx
  src/hooks/common/useLazyIntersectionObserver.ts
  src/hooks/queries/content/useContentDetailQuery.ts
  src/index.css
  src/pages/AdminPage.tsx
  src/pages/ContentDetailPage.tsx
  src/pages/HomePage.tsx
  src/pages/SearchPage.tsx
  src/types/content.d.ts
  tailwind.config.js
Labels: 🔧Fix

#43 [FEAT] [HIGH-55] 1차 QA 수정사항 반영
  src/components/Home/HomeContentContainer.tsx
  src/components/Home/organism/MainRecommendBanner.tsx
  src/components/common/Navigation/NavItem.tsx
  src/components/common/Navigation/NavigationBar.tsx
  src/components/shorts/molecules/ReelProgressBar.tsx
Labels: Review effort 2/5

#45 [FEAT] [HIGH-56] 쇼츠 QA수정사항 해결
  src/components/Home/HomeContentContainer.tsx
  src/components/common/Navigation/NavigationBar.tsx
  src/components/shorts/ShortsLayout.tsx
  src/components/shorts/organism/ReelCard.tsx
  src/hooks/queries/home/useRecommendQuery.ts
  src/hooks/queries/shorts/useShortsByIdQuery.ts
  src/hooks/queries/shorts/useShortsInfiniteQuery.ts
  src/hooks/shorts/useActiveShortsId.ts
  src/hooks/shorts/useShortsToShow.ts
  src/pages/ShortsPage.tsx
Labels: 🐛Bug, 🔧Fix, Review effort 3/5

#46 [FEAT] [HIGH-57] S3 파일 업로드 수정
  src/apis/common/getContentPresignedUrl.ts
  src/apis/common/getCurationPresignedUrl.ts
  src/apis/common/getPresignedUrl.ts
  src/components/My/MyLayout.tsx
  src/components/admin/content-modal.tsx
  src/components/common/Header.tsx
  src/components/common/atom/AnimatedButtonEntrance.tsx
  src/constants/api.ts
  src/hooks/common/useFileUpload.ts
  src/hooks/my/useCurationSubmit.ts
Labels: 🌟Feature, 🔨Refactor, Review effort 3/5

#48 [FEAT] [HIGH-59] 콘텐츠 상세, 쇼츠 페이지 시멘틱 태그 개선 및 메타데이터 처리
  index.html
  public/icons/favicon-16x16.png
  public/icons/favicon-32x32.png
  public/icons/favicon-48x48.png
  public/icons/favicon-64x64.png
  public/og-image.png
  public/robots.txt
  public/vite.svg
  src/App.tsx
  src/components/contentDetail/ContentDetailLayout.tsx
  src/components/contentDetail/molecules/ContentDetailHeader.tsx
  src/components/contentDetail/molecules/StarRating.tsx
  src/components/contentDetail/organism/ContentVideo.tsx
  src/components/contentDetail/organism/ReviewForm.tsx
  src/components/shorts/ShortsLayout.tsx
  src/components/shorts/organism/ReelCard.tsx
  src/components/shorts/organism/ReelCommentForm.tsx
  src/components/shorts/organism/ReelOverlay.tsx
Labels: 🐛Bug, 🔧Fix, Review effort 3/5

#49 [REFACTOR] [HIGH-61] 온보딩 및 마이 페이지 시맨틱 마크업
  src/components/My/molecule/CurationForm.tsx
  src/components/My/molecule/MyReviewItem.tsx
  src/components/My/molecule/Profile.tsx
  src/components/My/molecule/SearchContentList.tsx
  src/components/My/molecule/SelectedContentList.tsx
  src/components/My/organism/CreateCurationModal.tsx
  src/components/My/organism/CurationTab.tsx
  src/components/My/organism/MyCurationItem.tsx
  src/components/My/organism/ReviewTab.tsx
  src/components/OnBoarding/molecule/OnBoardingContentCard.tsx
  src/components/OnBoarding/organism/BirthYearSelect.tsx
  src/components/OnBoarding/organism/GenderSelect.tsx
  src/components/OnBoarding/organism/Name.tsx
Labels: 🔨Refactor
